# TODO local build go project in docker compose
# Postgres image + table init scripts
# Prometheus + Grafana references i guess
# Wire up postgres image into local build yadda yadda / https://github.com/jackc/pgx
